const data = [
  {
    id: 1,
    name: 'Bàn học sinh',
    import_date: '23/04/2020',
    type: 'Công cụ, dụng cụ',
    manager: 'Dương Lê Minh',
    status: 'mới',
    item_value: '470 000',
    total_value: '940 000',
    amount: '20',
    total_paid: '0',
    total_borrowed: '10',
    note: '',
  },
  {
    id: 1,
    name: 'Sách Lập trình hướng đối tượng',
    import_date: '23/04/2020',
    type: 'Sách, tài liệu',
    manager: 'Dương Lê Minh',
    status: 'mới',
    item_value: '80 000',
    total_value: '800000',
    amount: '10',
    total_paid: '0',
    total_borrowed: '4',
  },
  {
    id: 1,
    name: 'Bảng',
    import_date: '23/04/2020',
    type: 'Công cụ, dụng cụ',
    manager: 'Dương Lê Minh',
    status: 'mới',
    item_value: '200 000',
    total_value: '1200000',
    amount: '6',
    total_paid: '0',
    total_borrowed: '4',
    note: '',
  },
];
export default data;
